### ISSUE TITLE
osdep_service.c

### ISSUE THREAD

**Issue by helloyang520** [blackPantherOS/rtl8192fu#5]
/home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c: In function 'isFileReadable':
/home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2223:11: error: implicit declaration of function 'get_fs'; did you mean 'get_sa'? [-Werror=implicit-function-declaration]
 2223 |   oldfs = get_fs();
      |           ^~~~~~
      |           get_sa
/home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2223:11: error: incompatible types when assigning to type 'mm_segment_t' from type 'int'
/home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2224:3: error: implicit declaration of function 'set_fs'; did you mean 'sget_fc'? [-Werror=implicit-function-declaration]
 2224 |   set_fs(KERNEL_DS);
      |   ^~~~~~
      |   sget_fc
/home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2224:10: error: 'KERNEL_DS' undeclared (first use in this function); did you mean 'KERNFS_NS'?
 2224 |   set_fs(KERNEL_DS);
      |          ^~~~~~~~~
      |          KERNFS_NS
/home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2224:10: note: each undeclared identifier is reported only once for each function it appears in
/home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c: In function 'retriveFromFile':
/home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2261:12: error: incompatible types when assigning to type 'mm_segment_t' from type 'int'
 2261 |    oldfs = get_fs();
      |            ^~~~~~
/home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2262:11: error: 'KERNEL_DS' undeclared (first use in this function); did you mean 'KERNFS_NS'?
 2262 |    set_fs(KERNEL_DS);
      |           ^~~~~~~~~
      |           KERNFS_NS
/home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c: In function 'storeToFile':
/home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2296:12: error: incompatible types when assigning to type 'mm_segment_t' from type 'int'
 2296 |    oldfs = get_fs();
      |            ^~~~~~
/home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2297:11: error: 'KERNEL_DS' undeclared (first use in this function); did you mean 'KERNFS_NS'?
 2297 |    set_fs(KERNEL_DS);
      |           ^~~~~~~~~
      |           KERNFS_NS
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.o] Error 1
make[1]: *** [Makefile:1810: /home/yang/project/realtek-8192FU/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.10.27-1-lts/build'
make: *** [Makefile:2327: modules] Error 2

**Comment by JureSencar** [comment]
Same here on 
Ubuntu 20.04
5.11.0-37-generic

**Comment by blackPantherOS** [comment]
Try this version
https://github.com/blackPantherOS/dkms-rtl8192fu
